name: 删除工作流
on:
  workflow_dispatch:

  schedule:
    - cron: 0 16 * * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: ysxhub888/delete-older-releases@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_days: ${{ env.retain_days }}
